require 'rake'
require 'erb'

################################################################################
# Prepare
####
CRYPTO_ROOT = File.expand_path(File.dirname(__FILE__))
CRYPTO_LIB  = File.join(CRYPTO_ROOT, 'lib')
CRYPTO_SRC  = File.join(CRYPTO_ROOT, 'src')

CRYPTO_START = 'anchor.js'
CRYPTO_FINAL = File.join(CRYPTO_LIB, "#{File.split(CRYPTO_ROOT)[1]}.js")

require File.join(CRYPTO_ROOT, 'builder')

################################################################################
# Tasks
####
task :default => [:clean, :build]
task :build => :crypto # for external prerequisite definitions

task :clean do
  if File.exist? CRYPTO_FINAL
    File.delete CRYPTO_FINAL
    print " - " + CRYPTO_FINAL + "\n"
  end
end

task :crypto do
  Dir.chdir(CRYPTO_SRC) do
    File.open(CRYPTO_FINAL, 'w+') do |lib|
      lib << Builder::Anchor.new(CRYPTO_START)
      print " + " + CRYPTO_FINAL + "\n"
    end
  end
end
