require 'rake'
require 'erb'

################################################################################
# Prepare
####
QUERY_ROOT = File.expand_path(File.dirname(__FILE__))
QUERY_LIB  = File.join(QUERY_ROOT, 'lib')
QUERY_SRC  = File.join(QUERY_ROOT, 'src')

QUERY_START = 'anchor.js'
QUERY_FINAL = File.join(QUERY_LIB, "#{File.split(QUERY_ROOT)[1]}.js")

require File.join(QUERY_ROOT, 'builder')

################################################################################
# Tasks
####
task :default => [:clean, :build]
task :build => :query # for external prerequisite definitions

task :clean do
  if File.exist? QUERY_FINAL
    File.delete QUERY_FINAL
    print " - " + QUERY_FINAL + "\n"
  end
end

task :query do
  Dir.chdir(QUERY_SRC) do
    File.open(QUERY_FINAL, 'w+') do |lib|
      lib << Builder::Anchor.new(QUERY_START)
      print " + " + QUERY_FINAL + "\n"
    end
  end
end
