require 'rake'
require 'erb'

################################################################################
# Prepare
####
COOKIE_ROOT = File.expand_path(File.dirname(__FILE__))
COOKIE_LIB  = File.join(COOKIE_ROOT, 'lib')
COOKIE_SRC  = File.join(COOKIE_ROOT, 'src')

COOKIE_START = 'anchor.js'
COOKIE_FINAL = File.join(COOKIE_LIB, "#{File.split(COOKIE_ROOT)[1]}.js")

require File.join(COOKIE_ROOT, 'builder')

################################################################################
# Tasks
####
task :default => [:clean, :build]

task :clean do
  if File.exist? COOKIE_FINAL
    File.delete COOKIE_FINAL
    print " - " + COOKIE_FINAL + "\n"
  end
end

task :build do
  Dir.chdir(COOKIE_SRC) do
    File.open(COOKIE_FINAL, 'w+') do |lib|
      lib << Builder::Anchor.new(COOKIE_START)
      print " + " + COOKIE_FINAL + "\n"
    end
  end
end
