require 'rake'

################################################################################
# Prepare
####
ROOT = File.expand_path(File.dirname(__FILE__))
DIRS = ['type', 'cookie', 'crypto', 'query']
TIME = Time.now.utc

NODAY = false

LONGDIR = DIRS.max {|x,y| x.length <=> y.length}.length

require 'rake'
require 'erb'
require File.join(ROOT, 'builder')

################################################################################
# Setup
####
task :default do
  print [
    "Global tasks:",
    "  build (all)",
    "  clean (rm)",
    "  status (st)",
    "",
    "Script tasks:"
  ].join($/) + $/
end

DIRS.sort.each do |dir|
  require File.join(ROOT, dir, 'rake.inc')
end

################################################################################
# Tasks
####

desc "Build all library scripts"
task :build
task :all => :build

desc "Delete all library scripts"
task :clean
task :rm => :clean

desc "Check build status of library scrips"
task :status
task :st => :status
