require 'rake'
require 'erb'

################################################################################
# Prepare
####
TYPE_ROOT = File.expand_path(File.dirname(__FILE__))
TYPE_LIB  = File.join(TYPE_ROOT, 'lib')
TYPE_SRC  = File.join(TYPE_ROOT, 'src')

TYPE_START = 'anchor.js'
TYPE_FINAL = File.join(TYPE_LIB, "#{File.split(TYPE_ROOT)[1]}.js")

require File.join(TYPE_ROOT, 'builder')

################################################################################
# Tasks
####
task :default => [:clean, :build]
task :build => :type # for external prerequisite definitions

task :clean do
  if File.exist? TYPE_FINAL
    File.delete TYPE_FINAL
    print " - " + TYPE_FINAL + "\n"
  end
end

task :type do
  Dir.chdir(TYPE_SRC) do
    File.open(TYPE_FINAL, 'w+') do |lib|
      lib << Builder::Anchor.new(TYPE_START)
      print " + " + TYPE_FINAL + "\n"
    end
  end
end
